[package]
name = "hexil"
version = "0.1.0"
edition = "2021"
authors = ["Lily McCabe <lily@lilymccabe.ca"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
build-time = "0.1.3"
palette = { version = "0.7.3", default-features = false, features = ["std", "serializing"] }
parking_lot = { version = "0.12.1", features = ["hardware-lock-elision", "send_guard", "serde"] }
thiserror = "1.0.51"
tokio = { version = "1.35.0", features = ["tracing", "io-util", "macros", "sync", "fs", "full"] }
tracing = { version = "0.1.40", features = ["async-await"] }
tracing-appender = { version = "0.2.3", features = ["parking_lot"] }
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.18", features = ["parking_lot", "tracing", "tracing-serde"] }
wgpu = "0.18.0"
winit = { version = "0.29.4", features = ["serde"] }
