[workspace]
members = []
resolver = "3"

[workspace.package]
authors = ["Lily McCabe <hexil@lilymccabe.ca>"]
edition = "2024"

[package]
name = "hexil"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.100", features = ["backtrace"] }
bitflags = "2.11.0"
bytemuck = { version = "1.24.0", features = ["derive", "zeroable_maybe_uninit", "pod_saturating", "min_const_generics", "must_cast", "const_zeroed", "zeroable_atomics"] }
euclid = { version = "0.22.11", features = ["bytemuck", "mint", "serde"] }
itertools = "0.14.0"
palette = { version = "0.7.6", features = ["serializing", "bytemuck"] }
parking_lot = { version = "0.12.5", features = ["hardware-lock-elision", "serde"] }
pkg-version = "1.0.0"
proptest = "1.11.0"
raw-window-handle = { version = "0.6.2", features = ["std"] }
thiserror = "2.0.17"
tracing = "0.1.44"
vulkanalia = { version = "0.35.0", features = ["window", "libloading"] }
winit = { version = "0.30.13", features = ["mint", "serde"] }



[profile.dev]
opt-level = 1

[features]
extra-log-statements = []
default = ["extra-log-statements"]
