CMAKE_MINIMUM_REQUIRED(VERSION 4.2)

PROJECT(Hexil LANGUAGES C VERSION 0.1.0)

set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

set(CMAKE_C_STANDARD 23)
set(CMAKE_C_EXTENSIONS ON)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/$<CONFIGURATION>")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/$<CONFIGURATION>")


ADD_SUBDIRECTORY(./src ./obj)


add_custom_command(OUTPUT ${PROJECT_BINARY_DIR}/imgui)
