[package]
name = "generate_additional_metadata_functions"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
bitflags = "2.11.0"
itertools = "0.14.0"
prettyplease = "0.2.37"
proc-macro2 = "1.0.106"
quote = { version = "1.0.45", default-features = false }
vulkan-registry = "0.2.4"
