[package]
name = "hexil-render"
version.workspace = true
authors.workspace = true
description.workspace = true
readme.workspace = true
repository.workspace = true
publish.workspace = true
edition.workspace = true

[dependencies]
thiserror = "2.0.3"
vulkano = "0.34.1"

[lints]
workspace = true
