on:
  workflow_dispatch:
    jobs:
      Build releases:
        name: Build Windows release
        runs-on: windows-latest
        steps:
          run: cargo build --release
          uses: actions/upload-artifact@v4.0.0
          with:
            path: target/release/hexil.exe
            if-no-files-found: error
        
